spring:
  profiles:
    default: local
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect  # H2 전용 Dialect
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb  # 메모리 기반 H2 DB 사용
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 접근 경로 설정

  data:
    redis:
      host: localhost  # Redis 서버 호스트
      port: 6379       # Redis 서버 포트 (기본값: 6379)

server:
  port: 9002

logging:
  level:
    org.springframework.cache: trace

---
spring:
  config:
    activate:
      on-profile: dev
